config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static_pages#main_page'
  resources :tweets
  resources :profiles
  resources :follows, only: :create
  resources :hashtags, only: :show

end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  mount_uploader :picture, PicUploader
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	include Twitter::Extractor

	def get_hashtags
		self.extract_hashtags(self.content)
	end

	belongs_to :user

	validates :content, length: { maximum: 140 }
	validate :hashtags_are_created

	def hashtags_are_created
		begin
			transaction do
				@hashtags = self.get_hashtags
				@hashtags.each do |the_hashtag|
					if Hashtag.where(tag: the_hashtag).any?
						#do something
					else
						if Hashtag.create!(tag: the_hashtag)
							#do nothing
						else
							self.errors.add(:base, "Your hashtag #{the_hashtag} cannot be created")
						end
					end
				end
			end
		rescue
			self.errors.add(:base, "Your tweet has a bad hashtag")
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets	
  
  has_one :profile

  acts_as_followable
  acts_as_follower
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
	def create
		@user = User.find(params[:follows][:user])
		current_user.follow(@user)
		redirect_to tweets_path
	end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
	def show
		@hashtag = Hashtag.where(tag: params[:id]).first
		@tweets = Tweet.all
		if @hashtag
			@filtered_tweets = @tweets.select do |tweet|
				tweet.get_hashtags.include?(@hashtag.tag)
			end
		else
			@filtered_tweets = Array.new
			flash.now[:notice] = "there are no tweets with #{params[:id]}"
		end
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :authenticate_user!

	def new
		@profile = Profile.new
	end

	def create
		@profile = Profile.new(profile_params)
		@profile.user = current_user
		if @profile.save
			flash[:success] = "You have successfully created a profile"
			redirect_to new_tweet_path
		else
			render 'new'
		end
	end

	def profile_params
		params.require(:profile).permit(:first_name, :picture, :description)
	end

	def show
		@profile = Profile.find(params[:id])
		@tweets = Tweet.all
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def main_page
		if user_signed_in?
			if current_user.profile
				redirect_to new_tweet_path
			else
				redirect_to new_profile_path
			end
		end
	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	before_action :authenticate_user!

	def new
		@tweet = Tweet.new
	end

	def create
		@tweet = Tweet.new(tweet_params)
		@tweet.user = current_user
		if @tweet.save
			flash[:success] = "You have created a tweet"
			redirect_to new_tweet_path
		else
			render 'new'
		end
	end

	def index
		@tweets  = Tweet.all
	end

	def show
		@tweets = Tweet.where(user_id: params[:id])
	end

	def tweet_params
		params.require(:tweet).permit(:content)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/hashtags/show.html.erb
<ul class="list-group">
<% @filtered_tweets.each do |tweet| %>
	<% if tweet.user.profile %>
	<li class="list-group-item">
		<%= tweet.content %> | <%= link_to tweet.user.profile.first_name, profile_path(tweet.user.profile) %>
		<% if current_user.following?(tweet.user) %>
				<button type="button" class="btn btn-danger">Already Following</button>
		<% else %>
			<%= simple_form_for :follows, url: follows_path do |f| %>
				<%= f.input :user, as: :hidden, input_html: {value: 	tweet.user.id} %>
				<%= f.button :submit, value: 'follow', class: 'btn btn-large btn-success' %>
			<% end %>
		<% end %>
	</li>
	<% end %>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Htwitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "ILab Twitter", root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
   	<% if user_signed_in? %>
      <ul class="nav navbar-nav">
        	<li><%= link_to "New tweet", new_tweet_path %></li>
        	<li><%= link_to "Newsfeed", tweets_path %></li>
          <li><%= link_to "My tweets", tweet_path(current_user.id) %></li>
      </ul>
    <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li>
        	<% if user_signed_in? %>
				<%= link_to "Log Out", destroy_user_session_path, method: :delete %>
			<% else %>
				<%= link_to "Sign in", new_user_session_path %>
			<% end %>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Accounts <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% if user_signed_in? && current_user.profile %>
              <li><%= link_to "My profile", profile_path(current_user.profile) %></li>
            <% end %>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">

	<% flash.each do |key,value| %>
	<div class="alert alert-<%=key%>">
		<%= value %>
	</div>
	<% end %>
	<%= yield %>
</div>

</body>
</html>

app/views/profiles/new.html.erb
<%= simple_form_for @profile do |f| %>
	<%= f.input :picture %>
	<%= f.input :first_name %>
	<%= f.input :description %>
	<%= f.button :submit %>
<% end %>

app/views/profiles/show.html.erb
<ul class="list-group">
  <li class="list-group-item"><%= image_tag @profile.picture %></li>
  <li class="list-group-item"><%= @profile.first_name %></li>
  <li class="list-group-item"><%= @profile.description %></li>
</ul>

app/views/static_pages/main_page.html.erb
this is the main page

app/views/tweets/index.html.erb
<ul class="list-group">
<% @tweets.each do |tweet| %>
	<% if tweet.user.profile %>
	<li class="list-group-item">
		<%= tweet.content %> | <%= link_to tweet.user.profile.first_name, profile_path(tweet.user.profile) %>
		<% if current_user.following?(tweet.user) %>
				<button type="button" class="btn btn-danger">Already Following</button>
				<%= link_to "See Tweets", tweet_path(tweet.user) %>
		<% else %>
			<%= simple_form_for :follows, url: follows_path do |f| %>
				<%= f.input :user, as: :hidden, input_html: {value: 	tweet.user.id} %>
				<%= f.button :submit, value: 'follow', class: 'btn btn-large btn-success' %>
			<% end %>
		<% end %>
	</li>
	<% end %>
<% end %>
</ul>

app/views/tweets/new.html.erb
<%= simple_form_for @tweet do |f| %>
	<%= f.input :content %>
	<%= f.button :submit %>
<% end %>

app/views/tweets/show.html.erb
<ul class="list-group">
<% @tweets.each do |tweet| %>
	<% if tweet.user.profile %>
	<li class="list-group-item">
		<%= tweet.content %> | <%= link_to tweet.user.profile.first_name, profile_path(tweet.user.profile) %>
		<% if current_user.following?(tweet.user) %>
				<button type="button" class="btn btn-danger">Already Following</button>
		<% else %>
			<%= simple_form_for :follows, url: follows_path do |f| %>
				<%= f.input :user, as: :hidden, input_html: {value: 	tweet.user.id} %>
				<%= f.button :submit, value: 'follow', class: 'btn btn-large btn-success' %>
			<% end %>
		<% end %>
	</li>
	<% end %>
<% end %>
</ul>